# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keychain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keychain
  pod 'KeychainSwift'
  target 'KeychainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeychainUITests' do
    # Pods for testing
  end

end
